# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    
    # ACTION CRIADA ESPECILAMENTE PARA O CYPRESS    
    - name: Cypress run
      uses: cypress-io/github-actions@v2.8.2
      with:
        record: true
        group: 'Semana Agilizei'
        env:
        #PASS THE DASHBOARD RECORD KEY AS AN ENVIROMENT VARIABLE
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          
    #UPLOAD DE VIDEOS GERADOS
    - name: Upload Videos
      uses: actions/upload-artifact@v2.2.0
     if: always()
     with:
       name: videos
       path: cypress/videos
